enableGitInfo = true
enableRobotsTXT = true
baseURL = 'https://oli.works/'
languageCode = 'en-us'
defaultContentLanguage = 'de'
title = 'Oliver Jakoubek — Software & Beratung'
theme = 'oliworks'

[params]
    author = "Oliver Jakoubek"
    description = 'Beratung und Entwicklung datenbankbasierter Individualsoftware für KMUs – Oliver Jakoubek'

[menus]
  [[menus.main]]
    name = 'Start'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Portfolio'
    pageRef = '/projekt/'
    weight = 20

  [[menus.main]]
    name = 'Impressum'
    pageRef = '/impressum/'
    weight = 30

[taxonomies]
  techology = 'technologies'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.mark]
          enable = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
